export const amount_text = 'div[ng-hide="noAccount"] strong'
export const deposit_Link_to_open_btn = 'Deposit'
export const submit_btn = 'button[type="submit"]'
export const message = '[ng-show="message"]'
export const transaction_modal_open_btn = 'Transactions'
export const transaction_table_amount_text = 'tbody tr td:nth-child(2)'
export const enter_amount='input'